Repository integr8ly/tutorial-web-app, pull requests merged in 2018-10, with the labels that each got.

#77 Removed hard coded days & create threads.json
  docs/bin/buildJson.sh
  public/steelthreads/json/en/threads.json
  src/components/tutorialDashboard/tutorialDashboard.js
  src/pages/landing/landingPageMastHead.js
  src/pages/tutorial/task/task.js
  src/services/userServices.js
  src/styles/application/_landingPageMastHead.scss
Labels: Hacktoberfest, bug

#110 Updated with status for middleware services
  src/components/installedAppsView/InstalledAppsView.js
  src/pages/tutorial/__tests__/__snapshots__/tutorial.test.js.snap
  src/styles/application/_installedAppsView.scss
Labels: Hacktoberfest

#119 Updated with card changes for completion and progress bar.
  src/components/tutorialCard/tutorialCard.js
  src/components/tutorialDashboard/tutorialDashboard.js
  src/styles/application/_tutorialCard.scss
Labels: Hacktoberfest, bug

#106 add throbber on task page
  src/components/loadingScreen/loadingScreen.js
  src/components/loadingScreen/resources/RedHatLogo.png
  src/components/loadingScreen/resources/StartingServices_Final.svg
  src/components/loadingScreen/resources/backdrop.png
  src/components/loadingScreen/resources/throbber.apng
  src/pages/tutorial/task/task.js
  src/styles/application/_loadingScreen.scss
  src/styles/application/_taskLayout.scss
  src/styles/index.scss
Labels: bug

#143 Return empty object for walkthrough docs in mock mode.
  src/common/docsHelpers.js
Labels: Hacktoberfest, bug

#137 another attempt to add the lockfile
  .gitignore
  Dockerfile
  yarn.lock
Labels: bug
